on:
  push:
    branches: [dev]
  schedule:
    - cron: "0 0 * * 0,3"
  workflow_dispatch:

jobs:
  update_google:
    name: Collect & push updated data
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Collect data
        run: npm run collect
        env:
          GOOGLE_WEB_FONTS_API_KEY: ${{ secrets.GOOGLE_WEB_FONTS_API_KEY }}
      - name: "Push to `data` branch"
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: data
          FOLDER: data
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: "Updated for {sha}: {msg}"
          COMMIT_NAME: GitHub Workflows
          COMMIT_EMAIL: 121127418+fontpm@users.noreply.github.com